set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

install:
    uv sync --dev

test:
    just -f ~/ai/quality-control/justfile-python test

test-ci:
    just -f ~/ai/quality-control/justfile-python test-ci
