# OpenCode Config Architecture

## ⚠️ CRITICAL WARNINGS — READ FIRST

### 🚫 DO NOT EDIT opencode.json

This file is **auto-generated**. Any manual edits will be overwritten the next time
`scripts/build_config.py` runs.
Treat it as a build artifact, not source code.

### 🚫 .opencode subdirectories are IRRELEVANT to global config

The `.opencode/` directories in various project folders are local to those projects.
The **global config** lives at `~/.config/opencode` (symlinked to
`/home/dzack/ai/opencode`). Ignore any `.opencode/` folders you may find in
subdirectories.

### 🚫 DO NOT EDIT generated files in opencode/agents/

Managed markdown agents get regenerated by `permissions/main.py build`. Their
`permission` blocks are build output.
Edit the prompt slug source in `ai-prompts` or the compiler in `permissions/` instead.

### 🚫 DO NOT DUPLICATE AGENT METADATA

Descriptions, mode, model, temperature, and top_p live in the prompt frontmatter
provided by `ai-prompts`. Generated files in `opencode/agents/` append compiled
`permission` blocks to that canonical metadata.

### 🚫 MODEL POLICY: NO GEMMA OR PHI MODELS

**No Gemma or Phi models, ever.** These models are systematically banned across all
providers (OpenRouter, NVIDIA, GitHub, etc.)
due to persistent instruction-following failures, infinite tool loops, and context
degradation issues. Do not whitelist them under any circumstances.

### 🚫 DO NOT ADD MODULAR PIECES TO config_skeleton.json

The skeleton is for **top-level defaults only** (MCP, permissions, formatter, LSP).
Modular pieces belong in their own files:
- Providers → `configs/providers/*.json`
- Managed agents → `ai-prompts` + generated `../agents/*.md`

## TL;DR

**`opencode.json` is NOT the source of truth.** It's generated via two scripts:

1. `permissions/main.py` — compiles permissions + prompt metadata → `agents/*.md`
2. `scripts/build_config.py` — merges top-level config/provider JSON → `opencode.json`

To make config changes persist:

### For permissions changes:

1. Edit `opencode/permissions/` and/or the prompt in `ai-prompts`
2. Run `uv run --python .venv/bin/python permissions/main.py build`

### For model/provider/other changes:

1. Edit files in `configs/providers/`, `config_skeleton.json`, and/or `ai-prompts`
2. Run `uv run --python .venv/bin/python permissions/main.py build`
3. Commit the source files plus regenerated `agents/*.md` and `opencode.json`

## Directory Structure

```
configs/
├── config_skeleton.json   # Base template (top-level defaults, MCP, permissions)
├── providers/             # Provider configs (merged into opencode.json provider key)
│   ├── github-copilot.json
│   ├── opencode.json
│   └── ...
ai-prompts                # Canonical prompt library resolved by slug
../agents/                # Generated OpenCode markdown agents
```

## How scripts/build_config.py Works

1. Loads `config_skeleton.json` as the base
2. Merges all `providers/*.json` into `config["provider"]`
3. Writes the combined result to `opencode.json`

## Permissions: Two-Layer System

Permissions are managed in TWO steps:

### Step 1: permissions/main.py (Source of Truth)

Located at `opencode/permissions/` — defines permission logic via Python agent
definitions and writes markdown agents via:

- **Agent classes**: Name + prompt template path + permission layers
- **Rule sets / mixins**: Reusable permission composition logic
- **Prompt templates**: Metadata + prompt body from `ai-prompts`

This is the SINGLE SOURCE OF TRUTH for permission logic.

### Step 2: Apply and Build

```bash
# Compile permissions + prompt metadata -> agents/ and rebuild opencode.json
uv run --python .venv/bin/python permissions/main.py build
```

### What gets generated

- `configs/config_skeleton.json` — gets GLOBAL_PERMISSION (baseline)
- `agents/*.md` — get compiled permission blocks merged into prompt frontmatter

**Never edit permission blocks manually** — they're regenerated every time
`permissions/main.py build` runs.
Edit the source in `permissions/` instead.

## Agent Update Workflow

Agents are generated from prompt sources in
`~/opencode-plugins/clis/ai-prompts/prompts/`. `permissions/main.py build` fetches them
(first local, then via `uvx` from GitHub) and writes compiled output to
`~/.config/opencode/agents/`.

**To update an agent:**
1. Edit the source file in `~/opencode-plugins/clis/ai-prompts/prompts/` (e.g.
   `micro-agents/opencode-compaction.md`)
2. Commit and push to the ai-prompts repo
3. Run `uv run --python .venv/bin/python permissions/main.py build`

**Do NOT edit `~/.config/opencode/agents/` directly** — the next `build` will overwrite
it with the upstream content.

## Common Mistakes

| Mistake | Why It's Wrong |
| --- | --- |
| Editing opencode.json directly | Gets overwritten next time scripts/build_config.py runs |
| Editing agents/*.md manually | Gets overwritten next time permissions/main.py build runs |
| Forgetting to run permissions/main.py build | Prompt metadata and permissions do not reach agents/*.md |
| Forgetting to run scripts/build_config.py | Provider/default config changes don't appear in opencode.json |
| Committing only opencode.json | Source prompts and generated agents aren't updated |

## Model Provider IDs

When setting a model, use the format `provider/model-id`:

- `github-copilot/gpt-5-mini` — GitHub Copilot's best GPT model (0x/free)
- `nvidia/moonshotai/kimi-k2.5` — NVIDIA hosted Kimi K2.5
- `opencode/minimax-m2.5-free` — OpenCode's minimax M2.5 free
- `cursor-acp/auto` — Local Cursor ACP proxy

## Checking Current Settings

```bash
# Top-level default model
grep '^  "model":' opencode.json | head -1

# Subagent model count
grep -c "github-copilot/gpt-5-mini" opencode.json
```
